---
title: "9/17 class"
output: github_document
---

I'm an R Markdown document! 

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

```{r}
getwd()
```

```{r}
litters_df = read_csv(file = "/Users/Apple/Desktop/2024Fall/Data 1/Class R/2/9-17-class/data_import_examples/FAS_litters.csv")
```

```{r}
names(litters_df)
```

```{r}
litters_df = janitor::clean_names(litters_df)
names(litters_df)
```
```{r}
pups_df=read_csv("data_import_examples/FAS_litters.csv")

pups_df=janitor::clean_names(pups_df)

pups_df
```
use absolute path

```{r}
pups_df=read_csv("/Users/Apple/Desktop/2024Fall/Data 1/Class R/2/9-17-class/data_import_examples/FAS_litters.csv")

pups_df
```

```{r}
litters_df

tail(litters_df, 5)
```


missing data
```{r}
litters_df = 
    read_csv(file = "data_import_examples/FAS_litters.csv",
        na = c(".", "NA", "")
    )
litters_df=janitor::clean_names(litters_df)

pull(litters_df,gd0_weight)

```

what if we code 'group' as a factor variable?

```{r}
litters_df = 
    read_csv(file = "data_import_examples/FAS_litters.csv",
        na = c(".", "NA", ""),
    col_types = cols(
      Group = col_factor()
    )
)

head(litters_df)

```

##import an excel file

import MLB 2011 summary data

```{r}
mlb11_df = read_excel("data_import_examples/mlb11.xlsx", sheet = "mlb11", n_max = 20)

head(mlb11_df, 5)

```
read SAS file

```{r}
pulse_df = read_sas ("data_import_examples/public_pulse_data.sas7bdat")
pulse_df

```

##never use read.csv()
it will print everything in it
```{r}
litters_df = read.csv("data_import_examples/FAS_liters.csv")

```
never do this either
```{r}
litters_df$L

```










